on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release'}

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      # Set up R environment (ensure R is installed before running R commands)
      - uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2-branch

      # Clear R package cache (only after R is installed)
      - name: Clear R Package Cache
        run: |
          unlink("~/.R/renviron", recursive = TRUE, force = TRUE)
          unlink("~/.Rprofile", recursive = TRUE, force = TRUE)
          unlink("~/.cache/R", recursive = TRUE, force = TRUE)
          unlink("~/.local/share/R", recursive = TRUE, force = TRUE)
          if (dir.exists(Sys.getenv("R_LIBS_USER"))) {
            unlink(Sys.getenv("R_LIBS_USER"), recursive = TRUE, force = TRUE)
          }
        shell: Rscript {0}

      # Set CRAN Mirror
      - name: Set CRAN Mirror
        run: |
          options(repos = c(CRAN = "https://cran.r-project.org"))
          options(pkgType = "source")
        shell: Rscript {0}

      # Force Remove Any Installed parsnip Version
      - name: Remove Existing parsnip Version
        run: |
          if ("parsnip" %in% rownames(installed.packages())) {
            remove.packages("parsnip")
          }
        shell: Rscript {0}

      # Install Correct parsnip Version
      - name: Install parsnip 1.2.1
        run: |
          install.packages("remotes")
          remotes::install_version("parsnip", version = "1.2.1", repos = "https://cran.r-project.org", type = "source")
          if (packageVersion("parsnip") != "1.2.1") {
            stop("Error: parsnip did not install correctly!")
          }
        shell: Rscript {0}

      - name: Restart R Session
        run: Rscript -e 'q("no")'

      # Install R Dependencies Without Upgrading
      - name: Install R Dependencies Without Upgrading
        run: |
          remotes::install_deps(dependencies = TRUE, upgrade = "never")
          if (packageVersion("parsnip") != "1.2.1") {
            stop("Error: parsnip version changed after dependency installation!")
          }
        shell: Rscript {0}

      - name: Check Installed Package Dependencies
        run: Rscript -e 'print(tools::package_dependencies("parsnip", db = available.packages(), recursive = TRUE))'

      # Install and Test "text" Package
      - name: Install and Test "text" Package
        run: |
          install.packages("devtools")
          library(devtools)
          devtools::install_github("theharmonylab/topics")
          devtools::install_github("oscarkjell/text")
          text::textrpp_install(prompt = FALSE)
          text::textrpp_initialize(textEmbed_test = TRUE)
        shell: Rscript {0}

      # Session Info
      - name: Session Info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      # Run R CMD check
      - name: R CMD Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
          OMP_MAX_ACTIVE_LEVELS: 0
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      # Display testthat output
      - name: Display Testthat Output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
