on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release'}

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      # Set up R environment
      - uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2-branch

      # Install system dependencies (Linux only)
      - name: Install System Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libjpeg-dev libpng-dev libtiff-dev libcairo2-dev libxt-dev default-jdk
          sudo apt install -y libharfbuzz-dev libfribidi-dev
          sudo apt install -y libgomp1
          sudo apt install -y libxml2-dev libssl-dev libcurl4-openssl-dev
          sudo apt install -y openjdk-11-jdk

      # Install system dependencies (macOS only)
      - name: Install System Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install jpeg libpng libtiff cairo harfbuzz fribidi
          brew install openjdk
          sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
          export JAVA_HOME=$(/usr/libexec/java_home)
          echo "JAVA_HOME=$(/usr/libexec/java_home)" >> $GITHUB_ENV

      # Pin Conflicting Package Versions
      - name: Pin Conflicting Package Versions
        run: |
          install.packages("remotes")
          options(repos = c(CRAN = "https://cran.r-project.org"))
          remotes::install_version("jpeg", version = "0.1-8.1", repos = "https://cran.r-project.org")
          remotes::install_version("rJava", version = "0.9-14", repos = "https://cran.r-project.org")
          remotes::install_version("gridtext", version = "0.1.4", repos = "https://cran.r-project.org")
          remotes::install_version("mallet", version = "0.3.0", repos = "https://cran.r-project.org")
          remotes::install_version("ggwordcloud", version = "0.5.0", repos = "https://cran.r-project.org")
          remotes::install_version("topics", version = "1.0.0", repos = "https://cran.r-project.org")
        shell: Rscript {0}
