
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Virtual environment

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
#          - {os: macOS-latest,   r: 'release'}
#          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'release'}

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@v2-branch

      - uses: actions/setup-python@v2
        with:
           python-version: 3.12.0

      - name: Check python paths
        run: |
          python -c "import sys; print(sys.path)"
          which -a python python3

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'cat(remotes::system_requirements("ubuntu", "16.04"), sep = "\n")')
          sudo apt install libharfbuzz-dev
          sudo apt install libfribidi-dev

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}


      - name: MAC - Installing text and testing it
        if: runner.os == 'macOS'
        run:  |
          install.packages("devtools")
          library(devtools)
          devtools::install_github("oscarkjell/text")
          library(text)
          text::textrpp_install_virtualenv(envname = "textrpp_virtualenv", python_path = "/usr/local/bin/python3.9", prompt = FALSE)
          text::textrpp_initialize(virtualenv = "textrpp_virtualenv", refresh_settings = TRUE)
          text::textEmbed("hello")
        shell: Rscript {0}

      - name: UBUNTU - Installing text and testing it
        if: runner.os == 'Linux'
        run:  |
          install.packages("devtools")
          library(devtools)
          devtools::install_github("oscarkjell/text")
          library(text)
          text::textrpp_install_virtualenv(envname = "textrpp_virtualenv", python_path = "/usr/bin/python3", prompt = FALSE)
          text::textrpp_initialize(virtualenv = "textrpp_virtualenv", refresh_settings = TRUE)
          text::textEmbed("hello")
        shell: Rscript {0}


      - name: WINDOWS - Installing text and testing it
        if: runner.os == 'Windows'
        run:  |
          Sys.setenv(RETICULATE_PYTHON = "C:\\hostedtoolcache\\windows\\Python\\3.9.0\\x64")
          library(reticulate)
          reticulate::virtualenv_create("text_virtualenv", required = TRUE)
          reticulate::use_virtualenv("text_virtualenv", required = TRUE)
          reticulate::py_install("nltk", envname = "text_virtualenv")
          reticulate::py_install('transformers==4.12.5', envname = "text_virtualenv")
          reticulate::py_install('torch==1.7.1', envname = "text_virtualenv")
          reticulate::py_install("numpy", envname = "text_virtualenv")
          reticulate::py_config()
          library(text)
          text::textEmbed("hello")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
